[2025-01-12T17:46:50.747+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_date.md_ledger_account_s manual__2025-01-12T17:46:41.922374+00:00 [queued]>
[2025-01-12T17:46:50.763+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_date.md_ledger_account_s manual__2025-01-12T17:46:41.922374+00:00 [queued]>
[2025-01-12T17:46:50.764+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-12T17:46:51.022+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): md_ledger_account_s> on 2025-01-12 17:46:41.922374+00:00
[2025-01-12T17:46:51.029+0000] {standard_task_runner.py:60} INFO - Started process 5657 to run task
[2025-01-12T17:46:51.034+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_date', 'md_ledger_account_s', 'manual__2025-01-12T17:46:41.922374+00:00', '--job-id', '2605', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmp4qkqmo4u']
[2025-01-12T17:46:51.039+0000] {standard_task_runner.py:88} INFO - Job 2605: Subtask md_ledger_account_s
[2025-01-12T17:46:51.109+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_date.md_ledger_account_s manual__2025-01-12T17:46:41.922374+00:00 [running]> on host 711845a6becd
[2025-01-12T17:46:51.228+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='budanovsa' AIRFLOW_CTX_DAG_ID='insert_date' AIRFLOW_CTX_TASK_ID='md_ledger_account_s' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T17:46:41.922374+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-12T17:46:41.922374+00:00'
[2025-01-12T17:46:51.254+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T17:46:51.402+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-12T17:46:51.423+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_date, task_id=md_ledger_account_s, execution_date=20250112T174641, start_date=20250112T174650, end_date=20250112T174651
[2025-01-12T17:46:51.434+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T17:46:51.520+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO log.logt (execution_datetime, event_datetime, event_name)
        VALUES ('2025-01-12 17:46:41.922374', '2025-01-12T17:46:51.424675', 'md_ledger_account_s');
    , parameters: None
[2025-01-12T17:46:51.524+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-12T17:46:51.573+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-12T17:46:51.647+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
