[2025-01-12T19:22:52.170+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_date.create_log_sheme manual__2025-01-12T19:22:42.214698+00:00 [queued]>
[2025-01-12T19:22:52.186+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_date.create_log_sheme manual__2025-01-12T19:22:42.214698+00:00 [queued]>
[2025-01-12T19:22:52.188+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-12T19:22:52.488+0000] {taskinstance.py:2191} INFO - Executing <Task(SQLExecuteQueryOperator): create_log_sheme> on 2025-01-12 19:22:42.214698+00:00
[2025-01-12T19:22:52.493+0000] {standard_task_runner.py:60} INFO - Started process 7397 to run task
[2025-01-12T19:22:52.501+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_date', 'create_log_sheme', 'manual__2025-01-12T19:22:42.214698+00:00', '--job-id', '2719', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpzol182co']
[2025-01-12T19:22:52.508+0000] {standard_task_runner.py:88} INFO - Job 2719: Subtask create_log_sheme
[2025-01-12T19:22:52.583+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_date.create_log_sheme manual__2025-01-12T19:22:42.214698+00:00 [running]> on host 711845a6becd
[2025-01-12T19:22:52.696+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='budanovsa' AIRFLOW_CTX_DAG_ID='insert_date' AIRFLOW_CTX_TASK_ID='create_log_sheme' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T19:22:42.214698+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-12T19:22:42.214698+00:00'
[2025-01-12T19:22:52.697+0000] {sql.py:276} INFO - Executing: create schema if not exists "log";

create table if not exists
	log.logt (
		execution_datetime TIMESTAMP not null,
		event_datetime TIMESTAMP not null,
		event_name VARCHAR(100) not null
);

[2025-01-12T19:22:52.708+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T19:22:52.721+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T19:22:52.813+0000] {sql.py:450} INFO - Running statement: create schema if not exists "log";

create table if not exists
	log.logt (
		execution_datetime TIMESTAMP not null,
		event_datetime TIMESTAMP not null,
		event_name VARCHAR(100) not null
);
, parameters: None
[2025-01-12T19:22:52.831+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_date, task_id=create_log_sheme, execution_date=20250112T192242, start_date=20250112T192252, end_date=20250112T192252
[2025-01-12T19:22:52.839+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T19:22:52.912+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO log.logt (execution_datetime, event_datetime, event_name)
        VALUES ('2025-01-12 19:22:42.214698', '2025-01-12T19:22:52.833569', 'create_log_sheme');
    , parameters: None
[2025-01-12T19:22:52.917+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-12T19:22:52.959+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-12T19:22:53.009+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
